[general]
live_config_reload = true

[window]
# Размер окна при запуске
dimensions = { columns = 120, lines = 40 }
padding = { x = 12, y = 12 }
decorations = "Transparent"
opacity = 1
blur = true # работает в зависимости от системы (см. ниже)
startup_mode = "Windowed"

[font]
size = 13.0
offset = { x = 0, y = 1 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true

[colors.primary]
background = "#000000"
foreground = "#c0caf5"

[colors.normal]
black =   "#15161e"
red =     "#f7768e"
green =   "#9ece6a"
yellow =  "#e0af68"
blue =    "#7aa2f7"
magenta = "#bb9af7"
cyan =    "#7dcfff"
white =   "#a9b1d6"

[colors.bright]
black =   "#414868"
red =     "#f7768e"
green =   "#9ece6a"
yellow =  "#e0af68"
blue =    "#7aa2f7"
magenta = "#bb9af7"
cyan =    "#7dcfff"
white =   "#c0caf5"

[colors.cursor]
cursor = "#c0caf5"
text = "#1a1b26"

[colors.selection]
text = "#c0caf5"
background = "#33467C"

[selection]
save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 3

[mouse]
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
]