[general]
live_config_reload = true

[window]
# Размер окна при запуске
dimensions = { columns = 120, lines = 40 }
padding = { x = 12, y = 12 }
decorations = "Transparent"
opacity = 1
blur = true # работает в зависимости от системы (см. ниже)
startup_mode = "Windowed"

[font]
size = 13.0
offset = { x = 0, y = 1 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[colors.normal]
black   = "#21222c"
red     = "#ff5555"
green   = "#50fa7b"
yellow  = "#f1fa8c"
blue    = "#bd93f9"
magenta = "#ff79c6"
cyan    = "#8be9fd"
white   = "#f8f8f2"

[colors.bright]
black   = "#6272a4"
red     = "#ff6e6e"
green   = "#69ff94"
yellow  = "#ffffa5"
blue    = "#d6acff"
magenta = "#ff92df"
cyan    = "#a4ffff"
white   = "#ffffff"

[colors.cursor]
cursor = "#f8f8f2"
text   = "#282a36"

[colors.selection]
text       = "#f8f8f2"
background = "#44475a"

[selection]
save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 3

[mouse]
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
{ mouse = "Left", mods = "Control", action = "Copy" },
]
